
"""
Update annotated prescription list
Problems:
some rows in AB have the same drug name, but differing true/false ab status
Drugs_that_dong_belong is a list i assembled with all of the names of drugs that should be filtered out of the ab list.
Solution:
prescription_update_fxn() can be run to update the correct ab true/false sstatus and remove drugs that don’t belong to make the final ab yes/no prescription table called ABrx. 

"""

#problem: some rows in AB have the same drug name, but differing true/false ab status. this is updating any antibiotic row as true.

@memory.cache
def prescription_update_fxn(prescription_df):

	"""
    Update the ab annotated prescription table to include additional true antibiotics and remove false ones
    Args:
    -----
    prescription_df: df
        Path to the filename containing the output of the prescription table generated by yikuan in 01-Prescription_table.ipynb

    Returns:
    -----
    prescriptions: df
        Path to the created df
    """

    drugs_that_dont_belong =['Furosemide','Dextrose 50%','Vancomycin Oral Liquid',
                         'Erythromycin 0.5% Ophth Oint','NEO*IV*Furosemide',
                         'Nystatin','Orthopedic Solution','Neomycin-Polymyxin-Bacitracin Ophth. Oint',
                         'Bacitracin Ophthalmic Oint','Bacitracin Ointment','Lasix',
                         'dextrose','MetronidAZOLE Topical 1 % Gel','Enalaprilat',
                         'NEO*PO*Furosemide (10mg/1ml)','Metronidazole Gel 0.75%-Vaginal','Spironolactone',
                         'Heparin',
                        'voriconazole','valgancyclovir','chloroquine','tamiflu','mefloquine','foscarnet',
                         'fluconazole','vorconazole','quinine','ribavirin','gancyclovir','chloroquine',
                         'atovaquone','ambisome', 'acyclovir', 'Acyclovir']

	drugs_that_dont_belong=[w.lower() for w in drugs_that_dont_belong]
    prescriptions= prescription_df
    prescriptions_updated = list(prescriptions.loc[prescriptions.loc[:,"Antibiotics"]==True,'drug'].unique()) 
    true_ndc= prescriptions.loc[prescriptions.loc[:,"drug"].isin(prescriptions_updated),'ndc'].unique() 

    ABrx2= prescriptions.loc[prescriptions.loc[:,"ndc"].isin(true_ndc),:]
    ABrx2= ABrx2.loc[~ABrx2.loc[:,"drug"].str.lower().isin(drugs_that_dont_belong),:] #tilde transforms isin to notin()

    return(ABrx2)

ABrx = prescription_update_fxn(prescriptions)


